name: 'Change8 Dependency Check'
description: 'Analyze dependency updates for breaking changes and link to migration guides'
author: 'Change8'
branding:
  icon: 'alert-triangle'
  color: 'orange'

inputs:
  github-token:
    description: 'GitHub token for posting comments'
    required: true
  fail-on-breaking:
    description: 'Fail the action if breaking changes are found'
    required: false
    default: 'false'
  change8-service-key:
    description: 'Optional Change8 API service key for authenticated access'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
